/**
 * Thin HTTP client for the Imference API (https://imference.com/docs).
 *
 * Credits rail (Bearer API key):
 *   GET  /api/models          public model catalog
 *   GET  /api/formats         per-model formats (resolution/ratio)
 *   POST /generate            submit a generation (image or video, model-driven)
 *   GET  /credits/balance     remaining credits for the API key
 *   GET  /media/all           all media generated by the API key
 *
 * x402 rail (USDC on Base, signed with a wallet private key):
 *   POST /ondemand/generate      pay-per-generation at the model's catalog price
 *   POST /ondemand/credits/add   prepay credits onto an API key (min 100, max 1M)
 *
 * Status polling uses GET /ondemand/status — the shared, unauthenticated status
 * handler that serves requests from BOTH rails (404 = pending, 422 = failed,
 * 200 = done).
 */

import { createSigner, decodeXPaymentResponse, wrapFetchWithPayment } from "x402-fetch";
import { privateKeyToAccount } from "viem/accounts";
import type { Hex } from "viem";

export interface ImferenceConfig {
  baseUrl: string;
  apiKey?: string;
  /** EVM private key (0x-prefixed, 64 hex chars) holding USDC on Base for x402 payments. */
  walletPrivateKey?: string;
}

export interface ImModel {
  model_code: string;
  name?: string;
  description?: string;
  short_description?: string;
  medium_description?: string;
  image?: string;
  model_url?: string;
  prompt_pre?: string;
  prompt_negative?: string;
  steps_default: number;
  steps_min: number;
  steps_max: number;
  cfg_default: number;
  cfg_min: number;
  cfg_max: number;
  skip_default: number;
  skip_min: number;
  skip_max: number;
  scheduler_default?: string;
  queue?: string;
  format_code?: string;
  im_engine?: string;
  frames_default?: number;
  frames_min?: number;
  frames_max?: number;
  fps_default?: number;
  fps_min?: number;
  fps_max?: number;
  im_cost: number;
  [key: string]: unknown;
}

export interface ImFormat {
  model_code: string;
  format_code: string;
  name?: string;
  width: number;
  height: number;
  ratio?: string;
  description?: string;
  order: number;
  is_default: boolean;
}

/** /status and /media/all rows marshal Go struct fields verbatim (untagged). */
export interface MediaRow {
  RequestID: string;
  Kind: string;
  URL: string;
  Format: string;
  Seed: number;
  Timestamp: string;
}

export interface GeneratePayload {
  model: string;
  prompt: string;
  negative_prompt?: string;
  width?: number;
  height?: number;
  steps?: number;
  clip_skip?: number;
  guidance_scale?: number;
  seed?: number;
  batch_nbr?: number;
  num_frames?: number;
  fps?: number;
  img_url?: string;
  scheduler?: string;
  output_format?: string;
  output_compression?: number;
  aspect_ratio?: string;
  image_size?: string;
  resolution?: string;
  duration_seconds?: number;
  person_generation?: string;
}

export type StatusResult =
  | { state: "pending" }
  | { state: "failed"; error: string }
  | { state: "done"; media: MediaRow };

/** Settlement info decoded from the X-PAYMENT-RESPONSE header after an x402 payment. */
export interface PaymentReceipt {
  success?: boolean;
  transaction?: string;
  network?: string;
  payer?: string;
}

/** x402 credits top-up bounds (mirrors the API: min $0.10, max $1,000 per call). */
export const MIN_X402_CREDITS_TOPUP = 100;
export const MAX_X402_CREDITS_TOPUP = 1_000_000;

/** 1 credit = $0.001 = 1000 atomic USDC units (6 decimals). */
export function creditsToAtomicUsdc(credits: number): bigint {
  return BigInt(Math.ceil(credits)) * 1000n;
}

export class ImferenceError extends Error {
  constructor(
    message: string,
    public readonly status?: number,
  ) {
    super(message);
    this.name = "ImferenceError";
  }
}

export class ImferenceClient {
  constructor(private readonly config: ImferenceConfig) {
    if (config.walletPrivateKey && !/^0x[0-9a-fA-F]{64}$/.test(config.walletPrivateKey)) {
      throw new ImferenceError(
        "IMFERENCE_WALLET_PRIVATE_KEY must be a 0x-prefixed 64-hex-char EVM private key",
      );
    }
  }

  get hasApiKey(): boolean {
    return !!this.config.apiKey;
  }

  get hasWallet(): boolean {
    return !!this.config.walletPrivateKey;
  }

  /** Public address of the configured wallet (never exposes the key). */
  get walletAddress(): string | undefined {
    if (!this.config.walletPrivateKey) return undefined;
    return privateKeyToAccount(this.config.walletPrivateKey as Hex).address;
  }

  /**
   * fetch wrapped with the x402 payment flow: on a 402 challenge, signs an
   * EIP-3009 USDC transfer (Base mainnet) with the configured wallet and
   * retries with the X-PAYMENT header. maxAtomic caps what the wallet will
   * sign for, in atomic USDC units (6 decimals).
   */
  private async paymentFetch(maxAtomic: bigint): Promise<typeof fetch> {
    if (!this.config.walletPrivateKey) {
      throw new ImferenceError(
        "IMFERENCE_WALLET_PRIVATE_KEY is not set. The x402 rail needs an EVM wallet " +
          "holding USDC on Base to sign payments.",
      );
    }
    const signer = await createSigner("base", this.config.walletPrivateKey as Hex);
    return wrapFetchWithPayment(fetch, signer, maxAtomic) as typeof fetch;
  }

  private receipt(res: Response): PaymentReceipt | undefined {
    const header = res.headers.get("x-payment-response");
    if (!header) return undefined;
    try {
      return decodeXPaymentResponse(header) as PaymentReceipt;
    } catch {
      return undefined;
    }
  }

  private headers(auth: boolean): Record<string, string> {
    const h: Record<string, string> = { "Content-Type": "application/json" };
    if (auth) {
      if (!this.config.apiKey) {
        throw new ImferenceError(
          "IMFERENCE_API_KEY is not set. This tool requires an Imference API key " +
            "(get one and add credits at https://imference.com).",
        );
      }
      h["Authorization"] = `Bearer ${this.config.apiKey}`;
    }
    return h;
  }

  private url(path: string, query?: Record<string, string>): string {
    const u = new URL(path, this.config.baseUrl);
    for (const [k, v] of Object.entries(query ?? {})) u.searchParams.set(k, v);
    return u.toString();
  }

  private async parseError(res: Response): Promise<string> {
    try {
      const body = (await res.json()) as { error?: string };
      return body.error ?? `HTTP ${res.status}`;
    } catch {
      return `HTTP ${res.status}`;
    }
  }

  async listModels(): Promise<ImModel[]> {
    const res = await fetch(this.url("/api/models"), { headers: this.headers(false) });
    if (!res.ok) throw new ImferenceError(await this.parseError(res), res.status);
    const body = (await res.json()) as { models: ImModel[] };
    return body.models ?? [];
  }

  async listFormats(): Promise<ImFormat[]> {
    const res = await fetch(this.url("/api/formats"), { headers: this.headers(false) });
    if (!res.ok) throw new ImferenceError(await this.parseError(res), res.status);
    const body = (await res.json()) as { formats: ImFormat[] };
    return body.formats ?? [];
  }

  async generate(payload: GeneratePayload): Promise<{ request_id: string; kind: string }> {
    const res = await fetch(this.url("/generate"), {
      method: "POST",
      headers: this.headers(true),
      body: JSON.stringify(payload),
    });
    if (!res.ok) throw new ImferenceError(await this.parseError(res), res.status);
    return (await res.json()) as { request_id: string; kind: string };
  }

  /**
   * One status probe via the shared unauthenticated handler (serves both
   * rails). The API maps request state to HTTP codes:
   * 404 → still pending (or unknown id), 422 → generation failed, 200 → done.
   */
  async status(requestId: string): Promise<StatusResult> {
    const res = await fetch(this.url("/ondemand/status", { request_id: requestId }), {
      headers: this.headers(false),
    });
    if (res.status === 404) return { state: "pending" };
    if (res.status === 422) return { state: "failed", error: await this.parseError(res) };
    if (!res.ok) throw new ImferenceError(await this.parseError(res), res.status);
    const body = (await res.json()) as { data: MediaRow };
    return { state: "done", media: body.data };
  }

  async balance(): Promise<number> {
    const res = await fetch(this.url("/credits/balance"), { headers: this.headers(true) });
    if (!res.ok) throw new ImferenceError(await this.parseError(res), res.status);
    const body = (await res.json()) as { credits: number };
    return body.credits;
  }

  /**
   * Pay-per-generation via x402: POST /ondemand/generate. The server prices
   * the 402 challenge at the model's catalog cost; maxAtomicUsdc caps what
   * the wallet will sign (pass the model's im_cost via creditsToAtomicUsdc,
   * plus a small margin).
   */
  async generateX402(
    payload: GeneratePayload,
    maxAtomicUsdc: bigint,
  ): Promise<{ request_id: string; kind: string; payment?: PaymentReceipt }> {
    const payFetch = await this.paymentFetch(maxAtomicUsdc);
    const res = await payFetch(this.url("/ondemand/generate"), {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });
    if (!res.ok) throw new ImferenceError(await this.parseError(res), res.status);
    const body = (await res.json()) as { request_id: string; kind: string };
    return { ...body, payment: this.receipt(res) };
  }

  /**
   * Prepay credits onto an API key with one USDC payment (price = credits ×
   * $0.001). An empty apiKey makes the server mint and return a fresh key.
   */
  async addCreditsX402(
    credits: number,
    apiKey?: string,
  ): Promise<{ api_key: string; credits_added: number; payment?: PaymentReceipt }> {
    const payFetch = await this.paymentFetch(creditsToAtomicUsdc(credits) + 10_000n);
    const res = await payFetch(this.url("/ondemand/credits/add"), {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ credits, ...(apiKey ? { api_key: apiKey } : {}) }),
    });
    if (!res.ok) throw new ImferenceError(await this.parseError(res), res.status);
    const body = (await res.json()) as { api_key: string; credits_added: number };
    return { ...body, payment: this.receipt(res) };
  }

  async allMedia(): Promise<MediaRow[]> {
    const res = await fetch(this.url("/media/all"), { headers: this.headers(true) });
    if (res.status === 204) return [];
    if (!res.ok) throw new ImferenceError(await this.parseError(res), res.status);
    const body = (await res.json()) as { data: MediaRow[] };
    return body.data ?? [];
  }
}

/** A model produces video when its engine/queue is wan-video based (same rule as the API). */
export function isVideoModel(m: ImModel): boolean {
  return m.im_engine === "wan22" || (m.queue ?? "").startsWith("wan-video");
}
