/**
 * Thin HTTP client for the Imference API (https://imference.com/docs).
 *
 * Credits rail (Bearer API key):
 *   GET  /api/models          public model catalog
 *   GET  /api/formats         per-model formats (resolution/ratio)
 *   POST /generate            submit a generation (image or video, model-driven)
 *   GET  /credits/balance     remaining credits for the API key
 *   GET  /media/all           all media generated by the API key
 *
 * x402 rail (USDC on Base, signed with a wallet private key):
 *   POST /ondemand/generate      pay-per-generation at the model's catalog price
 *   POST /ondemand/credits/add   prepay credits onto an API key (min 100, max 1M)
 *
 * Status polling uses GET /ondemand/status — the shared, unauthenticated status
 * handler that serves requests from BOTH rails (404 = pending, 422 = failed,
 * 200 = done).
 */

import { createSigner, decodeXPaymentResponse, wrapFetchWithPayment } from "x402-fetch";
import { privateKeyToAccount } from "viem/accounts";
import { createPublicClient, erc20Abi, formatUnits, http } from "viem";
import { base } from "viem/chains";
import type { Hex } from "viem";

/** USDC contract on Base mainnet. */
const USDC_BASE = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913" as const;

export interface ImferenceConfig {
  baseUrl: string;
  apiKey?: string;
  /** EVM private key (0x-prefixed, 64 hex chars) holding USDC on Base for x402 payments. */
  walletPrivateKey?: string;
  /** Hard cap in USD on any single x402 payment, whatever the tool call asks for. */
  x402MaxUsdPerCall?: number;
  /** Cumulative cap in USD on x402 spend over this server process's lifetime. */
  x402SessionMaxUsd?: number;
  /** Base mainnet RPC URL for balance reads (default https://mainnet.base.org). */
  baseRpcUrl?: string;
}

export interface ImModel {
  model_code: string;
  name?: string;
  description?: string;
  short_description?: string;
  medium_description?: string;
  image?: string;
  model_url?: string;
  prompt_pre?: string;
  prompt_negative?: string;
  steps_default: number;
  steps_min: number;
  steps_max: number;
  cfg_default: number;
  cfg_min: number;
  cfg_max: number;
  skip_default: number;
  skip_min: number;
  skip_max: number;
  scheduler_default?: string;
  queue?: string;
  format_code?: string;
  im_engine?: string;
  frames_default?: number;
  frames_min?: number;
  frames_max?: number;
  fps_default?: number;
  fps_min?: number;
  fps_max?: number;
  im_cost: number;
  [key: string]: unknown;
}

export interface ImFormat {
  model_code: string;
  format_code: string;
  name?: string;
  width: number;
  height: number;
  ratio?: string;
  description?: string;
  order: number;
  is_default: boolean;
}

/** /status and /media/all rows marshal Go struct fields verbatim (untagged). */
export interface MediaRow {
  RequestID: string;
  Kind: string;
  URL: string;
  Format: string;
  Seed: number;
  Timestamp: string;
}

export interface GeneratePayload {
  model: string;
  prompt: string;
  negative_prompt?: string;
  width?: number;
  height?: number;
  steps?: number;
  clip_skip?: number;
  guidance_scale?: number;
  seed?: number;
  batch_nbr?: number;
  num_frames?: number;
  fps?: number;
  img_url?: string;
  scheduler?: string;
  output_format?: string;
  output_compression?: number;
  aspect_ratio?: string;
  image_size?: string;
  resolution?: string;
  duration_seconds?: number;
  person_generation?: string;
}

export type StatusResult =
  | { state: "pending" }
  | { state: "failed"; error: string }
  | { state: "done"; media: MediaRow };

/** Settlement info decoded from the X-PAYMENT-RESPONSE header after an x402 payment. */
export interface PaymentReceipt {
  success?: boolean;
  transaction?: string;
  network?: string;
  payer?: string;
}

/** x402 credits top-up bounds (mirrors the API: min $0.10, max $1,000 per call). */
export const MIN_X402_CREDITS_TOPUP = 100;
export const MAX_X402_CREDITS_TOPUP = 1_000_000;

/** 1 credit = $0.001 = 1000 atomic USDC units (6 decimals). */
export function creditsToAtomicUsdc(credits: number): bigint {
  return BigInt(Math.ceil(credits)) * 1000n;
}

/** USD → atomic USDC units (6 decimals). */
export function usdToAtomic(usd: number): bigint {
  return BigInt(Math.round(usd * 1_000_000));
}

export function atomicToUsd(atomic: bigint): number {
  return Number(atomic) / 1_000_000;
}

export class ImferenceError extends Error {
  constructor(
    message: string,
    public readonly status?: number,
  ) {
    super(message);
    this.name = "ImferenceError";
  }
}

export class ImferenceClient {
  /** Cumulative x402 spend this process, in atomic USDC units. */
  private sessionSpentAtomic = 0n;

  constructor(private readonly config: ImferenceConfig) {
    if (config.walletPrivateKey && !/^0x[0-9a-fA-F]{64}$/.test(config.walletPrivateKey)) {
      throw new ImferenceError(
        "IMFERENCE_WALLET_PRIVATE_KEY must be a 0x-prefixed 64-hex-char EVM private key",
      );
    }
  }

  get hasApiKey(): boolean {
    return !!this.config.apiKey;
  }

  get hasWallet(): boolean {
    return !!this.config.walletPrivateKey;
  }

  /** Public address of the configured wallet (never exposes the key). */
  get walletAddress(): string | undefined {
    if (!this.config.walletPrivateKey) return undefined;
    return privateKeyToAccount(this.config.walletPrivateKey as Hex).address;
  }

  get sessionSpentUsd(): number {
    return atomicToUsd(this.sessionSpentAtomic);
  }

  get spendingCaps(): { perCallUsd?: number; sessionMaxUsd?: number; sessionSpentUsd: number } {
    return {
      perCallUsd: this.config.x402MaxUsdPerCall,
      sessionMaxUsd: this.config.x402SessionMaxUsd,
      sessionSpentUsd: this.sessionSpentUsd,
    };
  }

  /**
   * Spending guard, enforced by this server regardless of what the tool call
   * asks for. Runs BEFORE any signing or network call.
   */
  private authorizeSpend(priceAtomic: bigint, label: string): void {
    const perCall = this.config.x402MaxUsdPerCall;
    if (perCall !== undefined && priceAtomic > usdToAtomic(perCall)) {
      throw new ImferenceError(
        `Payment blocked: ${label} costs $${atomicToUsd(priceAtomic).toFixed(3)}, above the ` +
          `per-call cap of $${perCall} (IMFERENCE_X402_MAX_USD). Raise the cap in the server ` +
          `environment if this spend is intended.`,
      );
    }
    const sessionMax = this.config.x402SessionMaxUsd;
    if (sessionMax !== undefined && this.sessionSpentAtomic + priceAtomic > usdToAtomic(sessionMax)) {
      throw new ImferenceError(
        `Payment blocked: ${label} ($${atomicToUsd(priceAtomic).toFixed(3)}) would push session ` +
          `spend past $${sessionMax} (IMFERENCE_X402_SESSION_MAX_USD; already spent ` +
          `$${this.sessionSpentUsd.toFixed(3)}). Restart the server or raise the cap to continue.`,
      );
    }
  }

  /**
   * fetch wrapped with the x402 payment flow: on a 402 challenge, signs an
   * EIP-3009 USDC transfer (Base mainnet) with the configured wallet and
   * retries with the X-PAYMENT header. maxAtomic caps what the wallet will
   * sign for, in atomic USDC units (6 decimals).
   */
  private async paymentFetch(maxAtomic: bigint): Promise<typeof fetch> {
    if (!this.config.walletPrivateKey) {
      throw new ImferenceError(
        "IMFERENCE_WALLET_PRIVATE_KEY is not set. The x402 rail needs an EVM wallet " +
          "holding USDC on Base to sign payments.",
      );
    }
    const signer = await createSigner("base", this.config.walletPrivateKey as Hex);
    return wrapFetchWithPayment(fetch, signer, maxAtomic) as typeof fetch;
  }

  private receipt(res: Response): PaymentReceipt | undefined {
    const header = res.headers.get("x-payment-response");
    if (!header) return undefined;
    try {
      return decodeXPaymentResponse(header) as PaymentReceipt;
    } catch {
      return undefined;
    }
  }

  private headers(auth: boolean): Record<string, string> {
    const h: Record<string, string> = { "Content-Type": "application/json" };
    if (auth) {
      if (!this.config.apiKey) {
        throw new ImferenceError(
          "IMFERENCE_API_KEY is not set. This tool requires an Imference API key " +
            "(get one and add credits at https://imference.com).",
        );
      }
      h["Authorization"] = `Bearer ${this.config.apiKey}`;
    }
    return h;
  }

  private url(path: string, query?: Record<string, string>): string {
    const u = new URL(path, this.config.baseUrl);
    for (const [k, v] of Object.entries(query ?? {})) u.searchParams.set(k, v);
    return u.toString();
  }

  /**
   * GET with 2 retries on network errors, 5xx and 529 (backoff 500ms/1500ms).
   * Only used for idempotent reads — POSTs (which charge) are never retried.
   */
  private async getWithRetry(url: string, headers: Record<string, string>): Promise<Response> {
    const delays = [500, 1500];
    for (let attempt = 0; ; attempt++) {
      try {
        const res = await fetch(url, { headers });
        if (res.status < 500 || attempt >= delays.length) return res;
      } catch (err) {
        if (attempt >= delays.length) throw err;
      }
      await new Promise((r) => setTimeout(r, delays[attempt]));
    }
  }

  private async parseError(res: Response): Promise<string> {
    try {
      const body = (await res.json()) as { error?: string };
      return body.error ?? `HTTP ${res.status}`;
    } catch {
      return `HTTP ${res.status}`;
    }
  }

  async listModels(): Promise<ImModel[]> {
    const res = await this.getWithRetry(this.url("/api/models"), this.headers(false));
    if (!res.ok) throw new ImferenceError(await this.parseError(res), res.status);
    const body = (await res.json()) as { models: ImModel[] };
    return body.models ?? [];
  }

  async listFormats(): Promise<ImFormat[]> {
    const res = await this.getWithRetry(this.url("/api/formats"), this.headers(false));
    if (!res.ok) throw new ImferenceError(await this.parseError(res), res.status);
    const body = (await res.json()) as { formats: ImFormat[] };
    return body.formats ?? [];
  }

  async generate(payload: GeneratePayload): Promise<{ request_id: string; kind: string }> {
    const res = await fetch(this.url("/generate"), {
      method: "POST",
      headers: this.headers(true),
      body: JSON.stringify(payload),
    });
    if (!res.ok) throw new ImferenceError(await this.parseError(res), res.status);
    return (await res.json()) as { request_id: string; kind: string };
  }

  /**
   * One status probe via the shared unauthenticated handler (serves both
   * rails). The API maps request state to HTTP codes:
   * 404 → still pending (or unknown id), 422 → generation failed, 200 → done.
   */
  async status(requestId: string): Promise<StatusResult> {
    const res = await this.getWithRetry(this.url("/ondemand/status", { request_id: requestId }), this.headers(false));
    if (res.status === 404) return { state: "pending" };
    if (res.status === 422) return { state: "failed", error: await this.parseError(res) };
    if (!res.ok) throw new ImferenceError(await this.parseError(res), res.status);
    const body = (await res.json()) as { data: MediaRow };
    return { state: "done", media: body.data };
  }

  async balance(): Promise<number> {
    const res = await this.getWithRetry(this.url("/credits/balance"), this.headers(true));
    if (!res.ok) throw new ImferenceError(await this.parseError(res), res.status);
    const body = (await res.json()) as { credits: number };
    return body.credits;
  }

  /**
   * Pay-per-generation via x402: POST /ondemand/generate. The server prices
   * the 402 challenge at the model's catalog cost — pass that cost so the
   * spending guards run against it and the wallet signs for exactly that
   * amount (+ $0.01 headroom for rounding).
   */
  async generateX402(
    payload: GeneratePayload,
    priceCredits: number,
  ): Promise<{ request_id: string; kind: string; payment?: PaymentReceipt }> {
    const priceAtomic = creditsToAtomicUsdc(priceCredits);
    this.authorizeSpend(priceAtomic, `generation with model '${payload.model}'`);
    const payFetch = await this.paymentFetch(priceAtomic + 10_000n);
    const res = await payFetch(this.url("/ondemand/generate"), {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });
    if (!res.ok) throw new ImferenceError(await this.parseError(res), res.status);
    this.sessionSpentAtomic += priceAtomic;
    const body = (await res.json()) as { request_id: string; kind: string };
    return { ...body, payment: this.receipt(res) };
  }

  /**
   * Prepay credits onto an API key with one USDC payment (price = credits ×
   * $0.001). An empty apiKey makes the server mint and return a fresh key.
   */
  async addCreditsX402(
    credits: number,
    apiKey?: string,
  ): Promise<{ api_key: string; credits_added: number; payment?: PaymentReceipt }> {
    const priceAtomic = creditsToAtomicUsdc(credits);
    this.authorizeSpend(priceAtomic, `credits top-up of ${credits} credits`);
    const payFetch = await this.paymentFetch(priceAtomic + 10_000n);
    const res = await payFetch(this.url("/ondemand/credits/add"), {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ credits, ...(apiKey ? { api_key: apiKey } : {}) }),
    });
    if (!res.ok) throw new ImferenceError(await this.parseError(res), res.status);
    this.sessionSpentAtomic += priceAtomic;
    const body = (await res.json()) as { api_key: string; credits_added: number };
    return { ...body, payment: this.receipt(res) };
  }

  /**
   * Download a generated media file. Restricted to http(s); returns the raw
   * bytes plus the response content type.
   */
  async downloadMedia(url: string): Promise<{ bytes: Buffer; contentType: string }> {
    const u = new URL(url);
    if (u.protocol !== "https:" && u.protocol !== "http:") {
      throw new ImferenceError(`Unsupported URL scheme '${u.protocol}' — expected http(s)`);
    }
    const res = await this.getWithRetry(url, {});
    if (!res.ok) throw new ImferenceError(`Download failed: HTTP ${res.status}`, res.status);
    return {
      bytes: Buffer.from(await res.arrayBuffer()),
      contentType: res.headers.get("content-type") ?? "application/octet-stream",
    };
  }

  /** USDC balance of the configured wallet on Base mainnet (read-only RPC call). */
  async usdcBalance(): Promise<{ address: string; usdc: number }> {
    const address = this.walletAddress;
    if (!address) {
      throw new ImferenceError(
        "IMFERENCE_WALLET_PRIVATE_KEY is not set — no wallet to read a balance for.",
      );
    }
    const rpc = createPublicClient({
      chain: base,
      transport: http(this.config.baseRpcUrl ?? "https://mainnet.base.org"),
    });
    const raw = await rpc.readContract({
      address: USDC_BASE,
      abi: erc20Abi,
      functionName: "balanceOf",
      args: [address as Hex],
    });
    return { address, usdc: Number(formatUnits(raw, 6)) };
  }

  async allMedia(): Promise<MediaRow[]> {
    const res = await this.getWithRetry(this.url("/media/all"), this.headers(true));
    if (res.status === 204) return [];
    if (!res.ok) throw new ImferenceError(await this.parseError(res), res.status);
    const body = (await res.json()) as { data: MediaRow[] };
    return body.data ?? [];
  }
}

/** A model produces video when its engine/queue is wan-video based (same rule as the API). */
export function isVideoModel(m: ImModel): boolean {
  return m.im_engine === "wan22" || (m.queue ?? "").startsWith("wan-video");
}
